FROM ubuntu:latest

RUN apt update

RUN apt install -y wget

RUN apt-get update && apt-get install -y apt-utils && apt-get install -y wget  && \ 
apt-get install -y lbzip2 && apt-get install -y gcc && apt-get install -y zlib1g-dev && \ 
apt-get install -y libbz2-dev && apt-get install -y liblzma-dev && \ 
apt-get install -y libncurses5-dev && apt-get install -y --reinstall make && \
apt-get install -y libcurl4-openssl-dev && apt-get install -y libssl-dev

RUN wget https://github.com/samtools/htslib/releases/download/1.8/htslib-1.8.tar.bz2 && \
lbzip2 -d htslib-1.8.tar.bz2 &&  tar xf htslib-1.8.tar &&  rm htslib-1.8.tar && \ 
cd  htslib-1.8 &&  ./configure --prefix=/usr/local/ &&  make &&  make install

RUN wget https://github.com/samtools/samtools/releases/download/1.8/samtools-1.8.tar.bz2 && \
lbzip2 -d samtools-1.8.tar.bz2 && tar xf samtools-1.8.tar  && rm samtools-1.8.tar && \ 
cd samtools-1.8 && ./configure --prefix=/usr/local/ && make && make install
