FROM ubuntu:latest

USER root

RUN apt-get update 

RUN apt-get install -y build-essential && apt-get install -y wget && \
apt-get install -y gzip && apt-get install -y autoconf && apt-get install -y zlib1g-dev && \
apt-get install -y libbz2-dev && apt-get install -y liblzma-dev && apt-get install -y libcurl4-gnutls-dev && \
apt-get install -y libssl-dev && apt-get install -y libncurses5-dev && apt-get install -y procps

RUN wget https://github.com/samtools/htslib/archive/1.10.2.tar.gz && tar -xzvf 1.10.2.tar.gz && rm 1.10.2.tar.gz && \
cd htslib-* && autoheader && autoconf && ./configure --enable-libcurl --enable-s3 --prefix=/ && make && make install && cd /

RUN wget https://github.com/samtools/samtools/archive/1.10.tar.gz && tar -xzvf 1.10.tar.gz && rm 1.10.tar.gz && cd samtools-* && \
autoheader && autoconf && ./configure --enable-libgsl --enable-perl-filters --prefix=/ && make && make install && cd /

WORKDIR /data/
