FROM ubuntu:latest

CMD ["bash"]

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8

ENV PATH=/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

RUN apt-get update --fix-missing

RUN apt-get install -y wget && apt-get install -y bzip2 && apt-get install -y ca-certificates && apt-get install -y libglib2.0-0 && \
apt-get install -y libxext6 && apt-get install -y libsm6 && apt-get install -y libxrender1 && apt-get install -y git && \
apt-get install -y mercurial && apt-get install -y subversion

RUN apt-get clean

RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \ 
/bin/bash ~/miniconda.sh -b -p /opt/conda && rm ~/miniconda.sh && /opt/conda/bin/conda clean -tipsy && \
ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
echo "conda activate base" >> ~/.bashrc && find /opt/conda/ -follow -type f -name '*.a' -delete && \
find /opt/conda/ -follow -type f -name '*.js.map' -delete && /opt/conda/bin/conda clean -afy

CMD ["/bin/bash"]

RUN apt-get update && apt-get install procps -y && conda install vcftools=0.1.16 -c bioconda && conda clean -a

WORKDIR /data/
